### ISSUE TITLE
pdal-native: jar asking for libc.musl-x86_64

### ISSUE THREAD

**Issue by romulogoncalves** [PDAL/java#6]
In the maven repository pdal-native is asking for libc.musl-x86_64. That leads to a linkage problem at runtime.

**Comment by pomadchin** [comment]
Hey! Thx for an immediate report, what os are you on (and Linux distribution if it’s linux)? Do you use RC2 from maven central?

**Comment by pomadchin** [comment]
Ok i could tack down the issue, it's because of the Alpine build.

**Comment by pomadchin** [comment]
The workaround for now is: 

```
apt-get install musl musl-dev -y
ln -s /usr/lib/ld-musl-x86_64.so.1 /usr/lib/libc.musl-x86_64.so.1
```

**Comment by pomadchin** [comment]
The easiest solution would be to build bindings under debian, as it has no dependency on musl.
However i'm wondering would it work under apline after all?

Will update images and publish `RC3` today evening. Thanks!

**Comment by romulogoncalves** [comment]
Hi

I am using Ubuntu 16.4. The jars were downloaded from maven repository using gradle. After spotting the issue we built the bindings from source and replaced the pdal-native jar, the linkage issues were gone.

Thanks for the quick fix.

**Comment by pomadchin** [comment]
Released RC3 and it sone would be avail, for now you can use this stagin repository to test RC3 jar: https://oss.sonatype.org/content/repositories/staging

**Comment by pomadchin** [comment]
Fixed in https://github.com/PDAL/java/tree/1.7.0-RC3
