### ISSUE TITLE
Question: Java/Kotlin Use Case

### ISSUE THREAD

**Issue by AlexandreBrown** [PDAL/java#64]
Hello,  
I was wondering if it was possible to use PDAL Java binding to overwrite the classification values of a LAS file from a list of new classification values ?
Ex:
LAS File 1
Classification fields: 0, 1,.., 2, 1

New classification values : 1, 0, ..., 3, 4

Goal: Create LAS File 2 with same content as LAS File 1 but with the classification field updated to use the new classification values.  
  
Is this use case supported?  
Thanks

**Comment by hobu** [comment]
PDAL does not support in-place rewriting of content, but you should be able to create a new file from an existing one with updated Classification (or any other Dimension's) attributes.

**Comment by AlexandreBrown** [comment]
@hobu Awesome, do you know where I could find documentation for how to do this?  
I'm new to PDAL so I'm trying to learn how it works exactly.

**Comment by hobu** [comment]
Complete the workshop https://pdal.io/en/latest/workshop/ to learn how to use PDAL to manipulate data. Please refrain from using tickets for support questions.
