### ISSUE TITLE
PDAL-java <= 1.6.0: with apt-get jni binary is missing

### ISSUE THREAD

**Issue by romulogoncalves** [PDAL/java#7]
Hi,

I am using Ubuntu and I have installed pdal using:
apt-get install pdal

The following was installed:
romulo:emma$ dpkg -l | grep pdal
ii libpdal-base5 1.6.0-1 xenial1
ii libpdal-plugin-greyhound 1.6.0-1 xenial1
ii libpdal-plugin-icebridge 1.6.0-1 xenial1
ii libpdal-plugin-pgpointcloud 1.6.0-1 xenial1
ii libpdal-plugin-python 1.6.0-1 xenial1
ii libpdal-plugin-sqlite 1.6.0-1 xenial1
ii libpdal-plugins 1.6.0-1 xenial1
ii libpdal-util5 1.6.0-1 xenial1
ii pdal 1.6.0-1 xenial1

Then I got the jar files:
io.pdal pdal_2.11 1.6.0

When I try to read a LAS file I am getting:
Message: Native library libpdaljni.1.4.so (/native/x86_64-linux/libpdaljni.1.4.so) cannot be found on the classpath.

Should that have be solved by the package installation apt-get install pdal?
Or is still required to install PDAL from sources?

If I am missing some step, please let me know.

**Comment by pomadchin** [comment]
Have you added `pdal-native` in the dependencies?

**Comment by pomadchin** [comment]
ah; yes for PDAL <= 1.7.0 you had to compile PDAL with JNI bindings.
Try to depend on 1.7.0 and to add native deps. There should be no changes in the API / calls to the PDAL API.

**Comment by pomadchin** [comment]
But still, compatibility for _native libs_ is not guaranteed. PDAL <= 1.7 has a special compilation flag `WITH_PDAL_JNI`

**Comment by romulogoncalves** [comment]
If I depend on 1.7.0 it works. 

The point I try to raise is that if an user uses **apt-get install pdal** for PDAL < 1.7 & >= 1.4 PDAL_JNI should also be installed, right?

**Comment by pomadchin** [comment]
Right

**Comment by pomadchin** [comment]
Closing this issue. It also looks like we only partially support PDAL of a version < 1.7.x, so keep your PDAL up to date ;)
