### ISSUE TITLE
JVM crash / fatal error

### ISSUE THREAD

**Issue by edigonzales** [PDAL/java#92]
I have a simple pipeline that crashes the jvm

```java
String json = """
{
    "pipeline": [
        {
            "type": "readers.las",
            "filename": "%s"
        },
        {
            "type": "writers.las",
            "filename": "%s",
            "compression": "laszip"
        }
    ]
}
            """.formatted(inputFile, outputFile);    
Pipeline pipeline = new Pipeline(json, LogLevel.Error());
pipeline.execute(); 
pipeline.close();
```

Error is like:

```java
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000012cad1ec2, pid=7207, tid=7683
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.10+7 (17.0.10+7) (build 17.0.10+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (17.0.10+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-amd64)
# Problematic frame:
# C  [libpdalcpp.16.2.0.dylib+0x342ec2]  pdal::PipelineManager::validateStageOptions() const+0x22
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/stefan/sources/p-agi_lidar_2023/hs_err_pid7207.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Error report file is attached. Any idea what goes wrong? I'm on an older Intel Mac running macOS Monterey (12.7.4). Dependencies used are: `io.pdal:pdal-native:2.6.2`and `io.pdal:pdal_3:2.6.2`. I installed the pdal binaries and libs with conda. Running PDAL in the terminal works perfectly.

[hs_err_pid7207.log](https://github.com/PDAL/java/files/14619262/hs_err_pid7207.log)

**Comment by pomadchin** [comment]
Hi @edigonzales, is there a reproducible example to try?

**Comment by edigonzales** [comment]
@pomadchin In the zip file, there is the java class and a csv with 2 lines containing urls to a zipped las file. The file will be downloaded, unzipped and then converted to a laz file with pdal. You can run it with jbang:

```
curl -Ls https://sh.jbang.dev | bash -s - preprocess.java
```

[Archive.zip](https://github.com/PDAL/java/files/14619395/Archive.zip)

**Comment by pomadchin** [comment]
Hi @edigonzales, the `pipeline.initialize()` step is missing. The crash happens due to the not initialized pipeline execution.

```java
var pipeline = new Pipeline(json, LogLevel.Error());
pipeline.initialize();
pipeline.execute(); 
pipeline.close();
```

Check the example from the [README.md](https://github.com/PDAL/java?tab=readme-ov-file#pdal-core-java) or from the [examples project](https://github.com/PDAL/java/blob/main/examples/pdal-jni/src/main/java/com/azavea/MainJava.java#L13)

**Comment by pomadchin** [comment]
There is a PR now as well to make initialize private and ensure it's called in the public Pipeline constructor: https://github.com/PDAL/java/pull/94

**Comment by edigonzales** [comment]
Thanks!
